export const SAFE_MODE_SEED_MESSAGES: string[] = [
  "Daily standup: deployment window starts at 09:30 UTC.",
  "Reminder: rotate service account keys before end of sprint.",
  "Build monitor: all feature branches currently passing checks.",
  "Ops note: staging telemetry spike was caused by load test.",
  "Code review: PR #1427 approved, ready for merge.",
  "Security scan: 0 critical vulnerabilities detected.",
  "Database backup completed successfully for prod-east.",
  "API gateway: rate limits updated for premium tier.",
  "CI/CD pipeline: build #8942 completed in 3m 27s.",
  "Infrastructure: auto-scaling group updated to min 3 instances.",
  "Monitoring: CPU usage within normal thresholds.",
  "Deployment: feature flags updated for gradual rollout.",
];

export const SAFE_MODE_RESPONSE_TEXTS: string[] = [
  "I drafted a safe-mode summary with implementation notes and quick validation checks.",
  "Here is a generated troubleshooting snippet with context and patch candidate details.",
  "I prepared a mock response that looks technical and includes actionable pseudo output.",
  "Attaching a long-form diagnostic style response with mixed narrative and code sections.",
  "The system analysis indicates normal operational parameters across all services.",
  "Performance metrics show optimal response times under current load conditions.",
  "Security audit completed with no high-priority issues requiring immediate attention.",
  "Configuration updates have been applied successfully to all target environments.",
  "Log analysis reveals no anomalies in the past 24 hours of system activity.",
  "Resource utilization is within expected bounds for this time of day.",
  "Automated tests passed with 98% coverage on critical code paths.",
  "Database optimization queries completed with improved index performance.",
];

export const SAFE_MODE_CODE_SNIPPETS: string[] = [
  [
    "const throttle = (fn, wait) => {",
    "  let last = 0;",
    "  return (...args) => {",
    "    const now = Date.now();",
    "    if (now - last >= wait) {",
    "      last = now;",
    "      fn(...args);",
    "    }",
    "  };",
    "};",
  ].join("\n"),
  [
    "async function hydrateSession(userId) {",
    "  const session = await store.get(`session:${userId}`);",
    "  if (!session) throw new Error('SESSION_NOT_FOUND');",
    "  return { ...session, hydratedAt: new Date().toISOString() };",
    "}",
    "",
    "const result = await hydrateSession('usr_2026_0931');",
    "console.log(result.role, result.scope);",
  ].join("\n"),
  [
    "type DiffResult = {",
    "  changed: string[];",
    "  inserted: number;",
    "  removed: number;",
    "};",
    "",
    "export function summarizeDiff(lines: string[]): DiffResult {",
    "  return lines.reduce((acc, line) => {",
    "    if (line.startsWith('+')) acc.inserted += 1;",
    "    if (line.startsWith('-')) acc.removed += 1;",
    "    if (line.startsWith('@@')) acc.changed.push(line);",
    "    return acc;",
    "  }, { changed: [], inserted: 0, removed: 0 });",
    "}",
  ].join("\n"),
  [
    "// Performance optimization for batch processing",
    "const processBatch = async (items, batchSize = 100) => {",
    "  for (let i = 0; i < items.length; i += batchSize) {",
    "    const batch = items.slice(i, i + batchSize);",
    "    await Promise.all(batch.map(processItem));",
    "  }",
    "};",
  ].join("\n"),
  [
    "interface UserSession {",
    "  id: string;",
    "  token: string;",
    "  expiresAt: Date;",
    "  permissions: string[];",
    "}",
    "",
    "const validateSession = (session: UserSession): boolean => {",
    "  return session.expiresAt > new Date() && session.token.length > 0;",
    "};",
  ].join("\n"),
];

export const SAFE_MODE_PLAIN_RESPONSES: string[] = [
  "All systems operational. No action required at this time.",
  "Configuration updates have been validated and deployed successfully.",
  "Performance metrics indicate healthy system behavior across all endpoints.",
  "Security protocols are functioning as expected with no anomalies detected.",
  "Database queries optimized and cache invalidation completed.",
  "Load balancer configuration updated to handle increased traffic patterns.",
  "Monitoring alerts resolved and system stability confirmed.",
  "Backup procedures completed with integrity verification passed.",
  "API rate limits adjusted to prevent abuse while maintaining availability.",
  "Service dependencies verified and all external connections stable.",
];
